name: Manual-build-gcc

on:
  workflow_dispatch:
jobs:
  build-gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: pushd build/gcc/ ; ./auto.sh ; popd
    - uses: actions/upload-artifact@v2
      with:
        name: bin
        path: "./build/gcc/bin"
    
